README.md
rmf_sandbox/.cargo/config.toml
rmf_sandbox/Cargo.toml

This PR adds the ability to build on windows. All you need to do is build using the standard rust steps. Essentially Bevy's dynamic feature is not supported on windows. This PR disables the dynamic feature.

Windows Tech Support

---

rmf_sandbox/src/building_map.rs
rmf_sandbox/src/camera_controls.rs
rmf_sandbox/src/despawn.rs
rmf_sandbox/src/save_load.rs
rmf_sandbox/src/site_map.rs
rmf_sandbox/src/spawner.rs
rmf_sandbox/src/warehouse_generator.rs

* Adds a basic test for serializing into yaml.
* Rework the despawner to be much simpler.
* `SiteMapRoot` is now a component instead of a resource, having it as a resource causes "use after despawn" problems where things still refer to the old entity after it is despawned.

Improve spawning system

---

rmf_sandbox/Cargo.lock
rmf_sandbox/src/save_load.rs
rmf_sandbox/src/site_map.rs
rmf_sandbox/src/spawner.rs
rmf_sandbox/src/traffic_editor.rs

Start adding keybindings to the traffic editor, for now feature to delete items and cancel selection.
Item deletion is pretty straightforward, vertices are a bit more involved since they need some bookkeeping to update the `LevelVerticesManager` hashmap, as well as a few checks to make sure they are not used by any edge otherwise things will go badly.
In the process of doing this PR I noticed that measurements weren't updated correctly when vertices property were changed, so addressed that as well.
Example of the feature below, there was no deleting implemented before so the behavior is brand new.
I couldn't figure out right now how to reset picking on pressing Escape so only the side panel is reset for now, left it as a TODO since it's just a minor annoyance. …

Add support for deleting objects and cancelling selection

---

.github/workflows/ci_web.yaml
.github/workflows/style.yaml
rmf_sandbox/rust-toolchain.toml

Back in April 2022, there was a minor regression in rust-nightly that forced us to peg the date of our toolchain. That has long since been fixed, so we can now return to "normal" Rust nightly. This will make the toolchain installation instructions for the WASM versions actually work again :tada: 
Signed-off-by: Morgan Quigley <morgan@osrfoundation.org>

return to normal rust-nightly, not a specific date

---

rmf_sandbox/src/lib.rs
rmf_sandbox/src/simulation_state.rs
rmf_sandbox/src/traffic_editor.rs

As part of my push towards visuallization of a crowd in rmf_sandbox, I am adding a "simulation preview" button. This button currently does nothing, however it enables a `SimulationState` resource. This will be needed when a user wants to preview the crowd simulations prior to running it in gazebo.
Signed-off-by: Arjo Chakravarty <arjo@openrobotics.org>

Adds a simulation preview button

---

rmf_sandbox/src/model.rs
scripts/blender/obj_to_glb.py

Our original conversion of the `.obj` mesh files of the models into `.glb` had an unintentional 90-degree rotation. A 90-degree rotation to counteract that was then hardcoded into the sandbox itself.
This PR removes the hardcoded 90-degree rotation and also provides a blender script to correctly convert `.obj` files to `.glb`. The models in the `sandbox://` server have already been updated.

Fix model rotation

---

rmf_sandbox/Cargo.lock
rmf_sandbox/src/building_map.rs
rmf_sandbox/src/level.rs
rmf_sandbox/src/save_load.rs

This PR fixes support for `.building.yaml` files that use `caretesian_meters` and also makes several fields optional so the file parser is less strict.

Fix support for cartesian_meters format

---

rmf_site_format/src/legacy/door.rs
rmf_site_format/src/legacy/error.rs

When implementing the conversion from the legacy `.building.yaml` format to the new `.site.ron` format, I misinterpreted the meaning of some of the door parameters. This PR fixes the conversion to reflect the real meaning of those parameters.

Correct the parsing of door properties

---

rmf_site_format/src/legacy/level.rs

As of https://github.com/open-rmf/rmf_traffic_editor/pull/418/files#diff-fb5555f6057f74143c5aeb3cbec283ba77df9b1aaf91780957d140986dce2168L223-L224  the Qt-based Traffic Editor no longer saves `flattened_x_offset` and `flattened_y_offset` fields for levels in its YAML output. This PR just makes those fields optional. They have always been set to zero anyway.

flattened_FOO_offset is no longer saved by Traffic Editor I

---

rmf_site_format/src/legacy/building_map.rs

Following the theme of https://github.com/open-rmf/rmf_site/pull/66 this should help make our building parsing more flexible towards the old building parameters that are optional.

Allow default values for crowd sim and lifts

---

index.html
scripts/deploy-web.sh
web/root_index.html

I introduced some errors into the web demo deployment script when migrating to `rmf_site`.
This PR fixes those errors and was used to generate the latest version of the web demo deployment: https://open-rmf.github.io/rmf_site/web/

Fix deploy script

---

.github/workflows/ci_linux.yaml
.github/workflows/ci_web.yaml
.github/workflows/ci_windows.yaml
.github/workflows/style.yaml

This should trigger each of the workflows whenever a change is made to `main` and also give us the ability to manually trigger any of the workflows from the GitHub UI.

Add more triggers for workflows to fix the badges

---

rmf_site_editor/src/site/lift.rs
rmf_site_editor/src/widgets/inspector/inspect_lift.rs
rmf_site_format/src/legacy/optimization.rs
rmf_site_format/src/lift.rs

The lift parameters were not being rendered quite how they were meant to be. This PR fixes that to have the rendered outcome match the originally intended meanings of the parameters.

More intuitive lift parameter meanings

---

rmf_site_editor/Cargo.toml
rmf_site_editor/src/interaction/cursor.rs
rmf_site_editor/src/lib.rs
rmf_site_editor/src/main.rs
rmf_site_editor/src/main_menu.rs
web/index.html

This PR adds support for specifying a map to load from the commands line, e.g. from the root directory of this repo:
```
cargo run --release -- assets/demo_maps/office.building.yaml
```
The general format is
```
cargo run <cargo options> -- <site editor options>
```
but right now the only command line argument we only support is specifying one file to load at startup.
This PR also takes the opportunity to fix some other aspects of the main menu behavior. In the past I've noticed cases where an extra file selection dialogue pops up and gets permanently stuck. I believe this PR should fix that issue as well.

Support CLI and improve main menu behavior

---

rmf_site_editor/Cargo.toml
rmf_site_editor/src/interaction/anchor.rs
rmf_site_editor/src/interaction/camera_controls.rs
rmf_site_editor/src/interaction/cursor.rs
rmf_site_editor/src/interaction/lane.rs
rmf_site_editor/src/interaction/mod.rs
rmf_site_editor/src/interaction/outline.rs
rmf_site_editor/src/interaction/preview.rs
rmf_site_editor/src/interaction/select_anchor.rs
rmf_site_editor/src/interaction/visual_cue.rs
rmf_site_editor/src/site/location.rs
rmf_site_format/src/category.rs

Until now we've allowed visual cues that are meant for the user (e.g. visualizations of lanes and anchors) to appear in the physical camera preview image. That behavior is not desirable since it means the physical camera preview is incorrect.
This PR eliminates that problem using bevy's `RenderLayers` feature. The `RenderLayers` component allows us to control what entities get rendered in which camera views. The non-physical entities are put into their own render layer which only gets rendered by the user-camera.
In order to prevent the user interaction highlights from showing in the physical cameras, I needed to tweak the upstream implementation of `bevy_mod_outline`. I've [opened an issue](https://github.com/komadori/bevy_mod_outline/issues/8) to ask the maintainer to open a branch for …

Prevent visual cues from showing for physical camera feeds

---

rmf_site_editor/src/interaction/camera_controls.rs
rmf_site_editor/src/interaction/outline.rs
rmf_site_editor/src/interaction/visual_cue.rs

This PR fixes some subtle issues with the way outlining was implemented for selection and hovering.
Previously when multiple objects were being outlined, their outlines would interfere with each other in ways that aren't intuitive or helpful. After this PR, outlines for anchors, selected, and hovered objects will all be drawn independently so they appear in an intuitive and helpful way. See the before and after for an illustration, and notice these details in the before picture:
* No outline was being drawn around the anchor
* The white outline around the desk gets cut off in the areas where the selected wall is in the background

Fix the apperance of outlines when hovering and selecting overlapping objects

---

rmf_site_editor/src/interaction/anchor.rs
rmf_site_editor/src/site/model.rs

Now models can be dragged around in the x/y plane by clicking and dragging.

Allow models to be dragged

---

rmf_site_format/src/legacy/building_map.rs

There are some parameters in the old crowdsim format that are not being parsed yet in the legacy parser of `rmf_site_format`. As a result loading some building files currently fails (e.g. the airport terminal demo world).
This PR simply has the legacy parser skip crowdsim entirely to side step this issue. We aren't using crowdsim data inside of the site editor yet anyway, so parsing it has no value at this time. We can revert this change in the future when we're ready to explore ways to migrate the legacy crowdsim data to a new format.

Ignore legacy crowdsim parsing

---

rmf_site_editor/src/site/assets.rs
rmf_site_editor/src/site/drawing.rs
rmf_site_editor/src/site/model.rs
rmf_site_editor/src/site_asset_io.rs
rmf_site_editor/src/widgets/icons.rs
rmf_site_editor/src/widgets/inspector/inspect_asset_source.rs
rmf_site_format/src/asset_source.rs

The static server that was previously used to host assets is no longer around :skull: . This PR will migrate those asset requests to [Fuel](https://app.gazebosim.org/dashboard)
Because the static server was used for non-asset things, like icons and wall textures, we need another solution for those types of assets. For lack of a better idea, I added a "Bundled" asset type, and manually bundle the icons and default wall texture at build time.
Currently this PR does not encode any error handling from Fuel. This needs to be added before this will behave as expected.

Use assets from Fuel instead of the previous static server

---

rmf_site_editor/src/lib.rs
rmf_site_editor/src/simulation_state.rs

This struct is currently unused. It is a vestige from an earlier time.

Remove SimulationState struct

---

.github/workflows/style.yaml

Use stable toolchain for style checks. We target `stable` in all the CI checks anyway, `let else` format merged in nightly broke our style CI.

Use stable toolchain for style CI checks

---

rmf_site_editor/src/workspace.rs
rmf_site_format/src/level.rs
rmf_site_format/src/site.rs

Fixes #130.
The fix is reasonably straightforward, just change the `Default` implementation of sites to have a new empty level. I'm not 100% sure putting a site ID of 0 is sound, and whether this would create any issue if we had multiple workspaces open

Fix panic with new workspaces

---

rmf_site_format/src/legacy/lift.rs

When importing projects containing lifts with rectangular shapes, things can go quite wrong, from swapped widths and depths to failure in importing the project.
This PR is little more than a bug report, it's a "hacky fix that seems to work", there might be a better fix but I'm not familiar with how lifts are stored and parsed in the site editor.
I just swapped widths and depths in the legacy lift importing code path, not sure how the coordinate system is supposed to be but this seems to fix all the scenarios I could find.
Test it!
* Create a world with a rectangular lift, for example change [this line](https://github.com/open-rmf/rmf_demos/blob/3f29a858ae64f2702696c5b1e5481c969c8f08a4/rmf_demos_maps/maps/hotel/hotel.building.yaml#L1046) to a large number like 10.0
* Open the map in …

POC fix for legacy lifts

---

rmf_site_editor/src/interaction/outline.rs

There seems to be an issue with outline rendering in wasm builds, as documented in https://github.com/komadori/bevy_mod_outline/issues/19.
This PR circumvents the issue by temporarily switching to Real outlines for wasm builds.
It's already been deployed for testing and can be verified [on the browser](https://open-rmf.github.io/rmf_site/)

Hotfix for outline issue in wasm

---

rmf_site_format/src/legacy/building_map.rs

This PR fixes map alignment when importing legacy projects that include a list of features / constraints but no fiducials, a typical case is a building with only one level (hence no fiducials) but one or more robot maps (hence the sets of constraints and features).
Previously, no level anchors were spawned so the optimization ran during map alignment would also transform the reference drawing and find an average of all the drawings. With this PR, level anchors are spawned and added to the fiducials in the position where the reference drawing is. The result is that the reference drawing will be "sticky" and stay in its original position with only the imported robot layers being translated.
I had to increase the scope of the reference drawing site id which required wrapping it in an …

Add level fiducials to reference drawing features

---

rmf_site_editor/Cargo.toml
rmf_site_editor/examples/extending_menu.rs
rmf_site_editor/src/lib.rs
rmf_site_editor/src/widgets/menu_bar.rs
rmf_site_editor/src/widgets/mod.rs

This is in the hopes of making downstream integration easier. Users may want to customize site editor to their own needs in order to integrate with proprietary formats or tools. By exposing site editor as a plugin, a user may embed site editor in their own bevy plugin.

Make Site Editor itself a `Plugin`

---

rmf_site_editor/src/interaction/category_visibility.rs
rmf_site_editor/src/interaction/mod.rs
rmf_site_editor/src/interaction/select_anchor.rs
rmf_site_editor/src/site/model.rs
rmf_site_editor/src/site/sdf.rs
rmf_site_editor/src/widgets/menu_bar.rs
rmf_site_editor/src/widgets/mod.rs
rmf_site_editor/src/workcell/keyboard.rs
rmf_site_editor/src/workcell/load.rs
rmf_site_editor/src/workcell/save.rs
rmf_site_editor/src/workcell/urdf.rs
rmf_site_format/src/workcell.rs

This PR adds support for collision meshes in sdf parsing and unifies the concept of site / workcell visual and collision to offer the same UX.
Collisions were previously ignored when parsing SDF files. Now they will be parsed and spawned, although they will not be visualized by default.
Visualization can be toggled via the "View" menu on the top bar. I had to do a minor refactor of the `CategoryVisibility` plugin to allow disabled visualization on app initialization.
To simplify the UX and remove duplicated components I removed the `WorkcellVisualMarker` and `WorkcellCollisionMarker` to use a single marker component for both site and workcell projects.
Loading the demo world should look and feel the same. By clicking on the `View` menu you should be able to enable visualization of …

Add collision parsing to SDF models

---

rmf_site_editor/src/main_menu.rs
rmf_site_editor/src/site/drawing_editor/mod.rs
rmf_site_editor/src/site/load.rs
rmf_site_editor/src/site/site_visualizer/mod.rs
rmf_site_editor/src/widgets/mod.rs
rmf_site_editor/src/workcell/load.rs
rmf_site_editor/src/workspace.rs

When trying to launch a site directly from the command line, a race condition was causing a state to not change correctly. An easy fix for this is to always use `overwrite_set` instead of simply `set` for changing states. We don't make use of the queuing or stacking features of states so `overwrite_set` is what we should've been using in the first place.
This PR also adds logging for all the state change errors in case a different problem appears in the future.

Use State::overwrite_set and log errors

---

rmf_site_editor/src/site/save.rs

Originally reported by @arjo129, when multiple workspaces are open site saving generates corrupted levels.
Specifically, a `HashMap` of levels is populated and entities update it based on its `SiteID` value. However, multiple entities can have the same `SiteID`, as long as they are in different workspaces, hence the level data of the saved site might be silently overwritten by entities that are children of a level with the same `SiteID` that however belongs to a different site.
Steps to reproduce:
* Open a map, for example the demo map.
* Create a new workspace by clicking on File -> New.
* Draw something
* Save the workspace.
The resulting save file will be corrupted and contain a mix of data from the first and the second workspace. This should be addressed by the PR.
Instead of checking …

Fix level saving when multiple workspaces are open

---

rmf_site_editor/src/site/georeference.rs
rmf_site_editor/src/widgets/menu_bar.rs
rmf_site_editor/src/widgets/mod.rs

Simple fix for a part of #188 (targeting specifically the georeference menus). If it looks good I'll port it to the rest of UI (i.e. `View` menu).
This PR changes the georeference systems to only run when the app is in the `SiteEditor` state, as well as adds systems that are triggered when entering / exiting the state that spawn / despawn the submenus and insert / delete the tracking resource.
Happy to achieve a similar effect another way but we should have ways to only show menus in specific states.

Make georeference menus only show in site editor state

---

README.md
web/index.html

I'm not sure why the `resize_canvas` function was written, but it hasn't been working correctly in a long time, and I just discovered that if we simply remove it, the canvas will rescale itself correctly on its own.
I'm also recommending people install specifically version 0.2.84 of wasm-bindgen-cli or else there will be errors generating the JavaScript bindings.

Fix the way the site editor resizes on the web

---

Cargo.toml
README.md
rmf_site_editor/Cargo.toml
rmf_site_editor/package.xml

Fix #202, as well as add rosdep keys.
ROS 2 doesn't play well with dynamic linking so disabling it by default, while adding a note on the README on how to reeanble it at compile time to speed up development.
I also added rosdep keys to package.xml so users that use ROS to run the workcell editor don't need to install any system dependency manually.
These changes make the site editor fully compatible with rosdep, colcon and ros2 run utilities.

Add rosdep key and remove dynamic linking by default

---

rmf_site_format/src/workcell.rs

Set the datum link to `<workcell_name>_workcell_link` if the workcell root has multiple children.

Apply workcell datum convention to dummy workcell link

---

Cargo.lock
rmf_site_editor/src/site/floor.rs

Shortly after #196 was merged I noticed just one more detail about the gap generation that wasn't quite right.
For sides of the cabin that don't have a door, we should just use a minimal gap instead of the cabin's gap parameter. There's no reason to automatically create extra gap around the sides of the lift without any doors. If the user wants fine-grained control of the floor around the lift then they can manually edit the floor accordingly. For automatic hole generation we should stick to only cutting exactly what's needed for the lift to function correctly.
Before:
After:
It also seems we accidentally regressed the lockfile with the last PR, so this will fix that as well.

Fix floor gap on sides of lift that do not have doors

---

rmf_site_format/src/legacy/nav_graph.rs
rmf_site_format/src/legacy/vertex.rs
rmf_site_format/src/lift.rs
rmf_site_format/src/misc.rs
rmf_site_format/src/site.rs

While working on SDF export, I noticed that several properties are missing, this PR brings us "closer" to all the features adding doors, lifts and orientation constraints. It also updates the TODOs to bring them up to date with what is needed since we will need to revisit this section.
I split this into a standalone PR since the SDF export is already becoming a very large change and this is somewhat orthogonal so it should be easier to review (and probably it would be better to scrutinize this a bit closer, since mistakes in an exported SDF are a lot easier to spot than mistakes in an exported navgraph).
I'll only be able to do full end to end testing when this is integrated with the SDF branch and we can export a full demo world, so this is somewhat experimental code (and parts like the …

Add a few more properties to legacy navgraphs

---

rmf_site_editor/src/site/assets.rs
rmf_site_editor/src/widgets/mod.rs

Fixes #208.
This is the upstream bug that tracks the reason for our panic https://github.com/bevyengine/bevy/issues/10377.
It has been fixed and released in 0.13 but we are on 0.12 as of now. As much as I'm always a big fan of updating we are cannot do it quite yet until `bevy_polyline` and `bevy_infinite_grid` are updated, and they seem to always lag about 1 version of bevy.
Luckily there seems to be a workaround in https://github.com/bevyengine/bevy/issues/10377#issuecomment-1858797002 that we can use until we migrate.
To test:
* Build the site editor in a colcon workspace (Note you might need to remove the root Cargo.toml file until https://github.com/colcon/colcon-cargo/pull/25 is solved.
* Try to run it with `ros2 run rmf_site_editor rmf_site_editor`.
Note that I could only test on …

Fix embedded asset path panic

---

rmf_site_format/src/legacy/lift.rs

The type of this legacy field is float not int. Stumbled upon this when importing the legacy `roscon_workshop` map, i.e. [here](https://github.com/open-rmf/roscon_workshop/blob/ab9f95e4ab38a7273737c728da59301bb168de78/roscon_maps/maps/workshop/workshop.building.yaml#L496), the following is returned:
```
2024-04-04T08:55:03.590297Z ERROR librmf_site_editor::workspace: Failed loading legacy building Message("invalid type: floating point `1.57`, expected i32", Some(Pos { marker: Marker { index: 55291, line: 496, col: 33 }, path: "lifts.lift.doors.door.motion_axis_orientation" }))
```
[Reference in traffic_editor where it is a double](https://github.com/open-rmf/rmf_traffic_editor/blob/a83d0e870aebfcbefe546985d55272e6024448bb/rmf_traffic_editor/gui/lift_door.h#L36)
Fix its type, it's actually …

Fix legacy motion_axis_orientation type to f32

---

rmf_site_format/src/alignment.rs

Legacy traffic editor allows having levels with no measurements, it actually only uses measurements for the reference level and uses fiducials instead to compute the transform between other levels and the reference.
The code path would do a divide by 0 if there was a level with no measurements and result in a NaN alignment / silent failure in importing the project.
This PR makes sure we don't divide by 0 and initializes the scale to the same "sensible" default that is used in traffic editor (5 cm per pixel).
To test it, try to run the site editor and import https://github.com/open-rmf/roscon_workshop/blob/main/roscon_maps/maps/workshop/workshop.building.yaml before and after this PR. The first will panic (panic is actually caused by an external library when we pass it NaN values, not the …

Fix level alignment when levels have no measurements

---

rmf_site_format/src/asset_source.rs

_Mostly_ address #213.
Mostly because there is still an issue when migrating between a relative and an absolute path that is not addressed by this PR but that is a bit of a hairier one.
When using the old file name as a path to migrate from, the path would have an additional `../`. The previous logic would substitute the filename in the old path and calculate a diff which wouldn't exactly work, for example
```
folder/map/map.building.yaml
folder/map/scan.png
folder/map/new_map.site.ron
../scan.png
```
This is wrong and I believe what we should be doing instead is setting `NEW` to be the _folder_ containing the file, so this PR changes to the following:
```
folder/map
scan.png
```
Just run the site editor opening a legacy map then hit `Ctrl-S` to save it as a site to a new file:
```
cargo …
```

Fix migrate relative paths computation

---

Cargo.lock
rmf_site_editor/src/main_menu.rs
rmf_site_editor/src/site/load.rs
rmf_site_editor/src/widgets/inspector/inspect_fiducial.rs
rmf_site_editor/src/widgets/inspector/inspect_texture.rs
rmf_site_editor/src/widgets/view_levels.rs
rmf_site_editor/src/workspace.rs
rmf_site_format/src/site.rs

The main purpose of this PR is to support creating new sites from scratch from the main menu. However I'm sneaking in a bug fix and a quality of life improvement that I came up with while testing the process of building sites from scratch:
* If a list of groups (e.g. fiducials, textures) is being filtered in the selection drop-down menu, include a `more...` item in the drop down menu that clears the filter
* Fix the level spawning UI to add all the components that are needed

Add main menu option for creating new site

---

rmf_site_editor/src/site/drawing.rs
rmf_site_editor/src/site/model.rs
rmf_site_editor/src/site/texture.rs
rmf_site_editor/src/workcell/urdf_package_exporter/generate_package.rs
rmf_site_format/src/asset_source.rs
rmf_site_format/src/legacy/building_map.rs
rmf_site_format/src/workcell.rs

The bevy asset loader has a very unfortunate behavior of panicking if it receives an asset path with invalid syntax.
To prevent that I've changed the implementation of `AssetSource` from providing `From<&AssetSource> for String` to `TryFrom<&AssetSource> for String`, forcing us to verify that the asset source can be converted into an asset path with correct syntax before we pass it along to the bevy asset loader.
There are some cases where we just want to get any string out of the asset source and don't need it to have valid syntax, so for that I created an unsafe `AssetSource` method that simply does what the String conversion used to do. But this forces us to use `unsafe` and verify that we don't need valid syntax before using it.
To A/B test the panicking behavior, you can simply load …

Sanitize asset paths before passing them to the loader

---

rmf_site_editor/src/site/save.rs
rmf_site_editor/src/site/sdf_exporter.rs
rmf_site_editor/src/workspace.rs
rmf_site_format/src/sdf.rs

This uses Site ID values in file names for the following benefits:
1. The filenames will be the same even as the names of entities change
2. The correct filenames will be produced even if duplicate names exist among different models

Use site ID to ensure unique file names

---

rmf_site_editor/src/site/save.rs

Fixes #224 
The function to assign site IDs to new entities was not being called for anchors that were children of lifts, hence the subsequent query to save the site would not find the anchor (its ID would be missing).
The fix is to make sure we assign a site ID to anchors that are children of the lift cabin.
To test:
* Create a new site.
* Create a lift.
* Add a lane that goes into the lift.
* Save the site.
Without this PR you should get this error:
```
ERROR librmf_site_editor::site::save: Unable to compile site: an object has a reference to an anchor that does not exist
```
With this PR it should save successfully.

Fix assigning site IDs to new lanes in lifts

---

Cargo.lock
rmf_site_editor/Cargo.toml
rmf_site_editor/src/keyboard.rs
rmf_site_editor/src/lib.rs
rmf_site_editor/src/main_menu.rs
rmf_site_editor/src/site/sdf_exporter.rs
rmf_site_editor/src/widgets/menu_bar.rs
rmf_site_editor/src/workspace.rs

Refactor workspace loading to use `bevy_impulse` workflows.
As noted in the title, first try at using the library so happy to hear ways I can do it better / more efficiently.
Previously we created channels and used a system that spawns a detached async task that sends messages to a channel (for file dialogs) and one that continuously polls that channel to see if any event has been received.
By contrast, now this is done in a workflow where the output of the file selecting is piped into the function that will use it.
I went for an API that removes events altogether and uses workflows instead.
This has, to my understanding, a few benefits:
* We can avoid the overhead of running systems that do nothing 99.99% of the time, note how this PR removes all workspace loading systems.
* We can just …

Move workspace loading to workflows

---

Cargo.lock
rmf_site_editor/src/site_asset_io.rs

Unlike all other asset types (i.e. `rmf-server://asset-path`), assets that start with `package://` must _retain_ their `package://` prefix since the downstream library we use to parse it expects it in that form. 
Manually append it

Fix package:// asset parsing

---

Cargo.lock
rmf_site_editor/src/site/deletion.rs

Currently when we select an entity to be deleted, it is sent as a `Delete` event to the `handle_deletion_requests` system and goes through a series of `if` conditions to filter out any entities that cannot/should not be deleted but processed in another manner. As we add in more plugins this system can become fairly bloated with various types of entities across the site editor.
This PR adds a series of BoxedSystems as a resource to the world that takes over some of the filtering work. The `Delete` events are read by the same `handle_deletion_systems` and goes through a vector of filter systems. If any entity should not be permanently deleted, e.g. temporarily removed or hidden, it can be filtered out in one of these systems. The set of entities left at the end of this filtering process …

Filter entities sent for deletion

---

rmf_site_editor/src/interaction/camera_controls/keyboard.rs
rmf_site_editor/src/interaction/camera_controls/utils.rs
rmf_site_editor/src/interaction/mod.rs
rmf_site_editor/src/widgets/mod.rs

This PR does a soft decoupling of the Interaction and Widget plugins. I can foresee downstream users not wanting the Widget plugin at all, for example if they want to embed the site editor into an Angular frame where Angular takes care of providing widgets.
I tested this by replacing [this block](https://github.com/open-rmf/rmf_site/blob/d05474aeb428f27c2ffe9fe02f026cff6c073b48/rmf_site_editor/src/lib.rs#L221-L223) with just
```
app.add_plugins( MainMenuPlugin);
```
and then running
```
cargo run --release -- assets/demo_maps/office.building.yaml
```
and using Shift + arrow keys to see that the rotation is handled correctly.

Remove hard dependency on UserCameraDisplay for Interaction plugin

---

.github/workflows/ci_web.yaml
Cargo.lock
rmf_site_editor/Cargo.toml

Fixes #251 by pinning wasm-bindgen in both `Cargo.lock` and CI.
Pin the package, it's just a temporary stopgap but it should:
* Avoid all the spurious CI failures we get whenever a new release is triggered.
* Become an actual compile time error when it won't work anymore (other dependency requires higher version of the package), rather than the current silent failure

Pin wasm-bindgen to 0.2.93

---

README.md
rmf_site_editor_web/Cargo.toml

Following up on #253 this updates the README so users know which specific version of bindgen to install.

Update readme so bindgen installation matches what we need

---

rmf_site_editor/src/interaction/cursor.rs
rmf_site_editor/src/site/load.rs
rmf_site_editor/src/site/mod.rs
rmf_site_editor/src/site/model.rs
rmf_site_editor/src/site/save.rs
rmf_site_editor/src/site/scenario.rs
rmf_site_format/src/legacy/building_map.rs
rmf_site_format/src/legacy/model.rs
rmf_site_format/src/misc.rs
rmf_site_format/src/model.rs
rmf_site_format/src/sdf.rs
rmf_site_format/src/site.rs

This PR addresses one of the issues in https://github.com/open-rmf/rmf_site/issues/254 regarding the use of SiteParent in the site editor. Other than using it to store the parent entity on file, it should not be used in the codebase and instead we can query the built-in `Parent` directly.
This PR also makes it mandatory for each model instance to have a level entity set as its `Parent` at loading/creation, removing the need to assign it as a child to the site entity if there are no parents found. Model instances without a `Parent` will not be saved to file. Like before, any orphan instances found will be added as children to the current level entity. In the event a current level can't be found, we add a diagnostic issue.

Do not query SiteParent

---

rmf_site_editor/src/widgets/inspector/inspect_model_description/inspect_collision.rs
rmf_site_editor/src/widgets/inspector/inspect_model_description/inspect_mobility.rs
rmf_site_editor/src/widgets/inspector/inspect_model_description/inspect_robot_properties.rs
rmf_site_editor/src/widgets/inspector/mod.rs

This PR implements Recall for RobotPropertyKinds such that if a Recall value is available in the world and `update_robot_property_kind_components` receives a default value of the RobotPropertyKind, the recalled value will be used to update property kind. Otherwise, we will insert the default value. The `RecallPropertyKind` trait is also introduced to enable access to the recalled value for each property kind via `assume()`.
This fixes the current behavior where the value resets to default if the property kind is re-selected or switched.

Implement RecallPlugin for RobotPropertyKind

---

rmf_site_editor/src/site/anchor.rs
rmf_site_editor/src/site/drawing_editor/alignment.rs
rmf_site_editor/src/site/fuel_cache.rs
rmf_site_editor/src/site_asset_io.rs
rmf_site_format/src/anchor.rs
rmf_site_format/src/camera_poses.rs
rmf_site_format/src/legacy/nav_graph.rs
rmf_site_format/src/sdf.rs

Replaced non-critical .expect()s, for instance, the ones that only prints out a failure if fails. I'm still not sure what's the best case to handle the expect()s that is inside a function returning an expected type.
An example:
https://github.com/open-rmf/rmf_site/blob/809f44c92502e26214fd8c5da41db0937ac9d9b3/rmf_site_editor/src/interaction/cursor.rs#L149C1-L153C11
Here, the trait FromWorld's implementation of from_world always expects the function to return the Self object, meaning that it cannot fail. However, in the case that there are errors in creating interaction or site assets, I think it should return an Err object, and handled properly by callers of the from_world function. The other option is to keep the return Self type, but provide default value in case of such errors.
Part of …

replaced a few expects

---

rmf_site_editor/src/site/scenario.rs
rmf_site_editor/src/widgets/view_model_instances.rs

In the site editor, we can observe how many scenarios a model instance is included (visible) in by hovering over the model instance name. However, the current method of counting scenarios leads to an inaccurate result, as it takes `InstanceModifier::Inherited` as included, instead of checking what visibility the modifier is inheriting. This PR fixes the error. 
Additionally, in the unlikely case where visibility information for an instance cannot be found for the current scenario, the current editor sets it to visible but does not update the modifier data. This PR also updates that by sending an `UpdateInstance` event.

Fix inaccurate scenario count

---

Cargo.lock
rmf_site_editor/Cargo.toml
rmf_site_editor/src/site/floor.rs
rmf_site_editor/src/site/wall.rs
rmf_site_editor/src/widgets/inspector/inspect_asset_source.rs
rmf_site_format/Cargo.toml

Since https://github.com/open-rmf/rmf_site/pull/281 we've had a couple of bugs and housekeeping items to follow up:
- Use updated release / branches for `bevy_mod_outline`, `bevy_gltf_export`, and `ron`
- Extra `AssetSource` ComboBox in inspector, causing unnecessary widget for models/floors/walls and errors for duplicate ComboBox id
- In the widget implementation we fix this by returning early if the selected entity is a non-group entity that does not have any affiliated group entity (e.g. models). This ensures that the `AssetSource` widget won't be duplicated for group/non-group affiliations.
- Fix wall and floor meshes missing during creation
- We were doing mutable borrows of `Mesh3d` to update wall/floor meshes during creation when moving anchors around. With the migration it somehow …

Migration follow-up: version bumps and bug fixes

---

rmf_site_editor/src/interaction/camera_controls/cursor.rs

During the migration to 0.16 we broke the logic for the camera controls when the cursor is hovering over a blank void. As a result the camera suddenly halts when the cursor tries to cross a void, and the user cannot do any panning or orbiting if they start over a void.
This PR fixes the logic for how we handle cases where there's nothing under the cursor to pick.

Fix camera controls when the cursor is over a void

---

.cargo/config.toml
rmf_site_editor/src/interaction/mod.rs
rmf_site_editor/src/lib.rs
rmf_site_editor/src/main_menu.rs
rmf_site_editor/src/site/headless_export.rs
rmf_site_editor/src/site/load.rs
rmf_site_editor/src/site/mod.rs
rmf_site_editor/src/site/model.rs
rmf_site_editor/src/site/save.rs
rmf_site_editor/src/site/sdf_exporter.rs
rmf_site_editor/src/widgets/icons.rs
rmf_site_editor/src/widgets/inspector/inspect_model_description/inspect_robot_properties.rs
rmf_site_editor/src/widgets/mod.rs
rmf_site_editor/src/widgets/sdf_export_menu.rs
rmf_site_editor/src/widgets/view_nav_graphs.rs
rmf_site_editor/src/workspace.rs

This PR introduces a few improvements to loading files, importing, and exporting:
* The load dialog will look filter to include all `.building.yaml`, `.site.ron`, and `.site.json` by default, whereas it used to bias in favor of `.building.yaml`.
* The nav graph importing feature is now in File. The UI for this could probably be improved further, but for now at least it's reduced clutter in the Properties panel.
* There is now an option to export either/both SDF files and nav graphs in headless mode. You specify a different export path for each.

Improve load / import / export

---

crates/rmf_site_format/src/legacy/building_map.rs

Fixes duplicate robots spawned on every level reported in https://github.com/open-rmf/rmf_site/issues/315. Remaining of the ticket will be addressed in a separate PR.

Spawn robots on their respective levels only

---

crates/rmf_site_format/src/sdf.rs

Fix https://github.com/open-rmf/rmf_site/issues/317
Just use the model instance rather than the model description name. I suspect using model descriptions would also have failed as soon as duplicated models were spawned in a level.
We follow [OSRA's policy on GenAI tools](https://github.com/openrobotics/osrf-policies-and-procedures/blob/main/OSRF%20Policy%20on%20the%20Use%20of%20Generative%20Tools%20(%E2%80%9CGenerative%20AI%E2%80%9D)%20in%20Contributions.md)

Fix floor toggle SDF plugin

---

crates/rmf_site_editor/src/site/save.rs

Targets https://github.com/open-rmf/rmf_site/issues/340 to add better error handling for scenario saving.
Note that `BrokenAffiliation` and the newly introduced `EmptyAffiliation` are different: `BrokenAffiliation` points to an existing entity wrapped in `Affiliation` that cannot be queried from its intended group, while `EmptyAffiliation` alerts users of an empty `Affiliation` when it should always be populated.

Better error handling for saving scenarios

---

Cargo.lock
Cargo.toml
crates/rmf_site_editor/src/site/mod.rs

It's been too long, the [upstream PR that we need](https://github.com/bevyengine/bevy/pull/19064) seems to be semi-abandoned, this workaround also forces downstream users to rely on the same custom bevy version.
Just add a workaround in the code instead. Specifically, the "guilty" bevy system is scheduled to run [after](https://github.com/bevyengine/bevy/pull/19064/files#diff-5db119571c62eac9218400a8191eee2417503cd13d3921cd711e5a7fecf8f936L291) `AssetEvents`, if we schedule all our systems to run _before_ `AssetEvents`, we should be able to get all our changes in. Furthermore, because of the automatically inserted command flush, all entities should be spawned before the system that used to panic is run.
I only tested it with lane spawning that seems to be fine, if you comment the only …

Remove dependency on custom bevy

---

crates/rmf_site_camera/src/systems.rs

This PR closes https://github.com/open-rmf/rmf_site/issues/351 to fix misaligned outlines when in 2D drawing mode. It turns out that the active camera being used to render outlines was wrong - `is_active` for children cameras for both Perspective and Orthographic modes weren't being updated.

Propagate is_active to camera children

---

Cargo.toml
crates/rmf_site_editor/src/interaction/user_camera.rs
crates/rmf_site_editor/src/lib.rs

Fixes #390 
Change detection for `GlobalTransform` triggers every time the mouse is moved and it causes the component to be inserted on a deleted entity. By contrast, the one for `Transform` only triggers, correctly, when the actual anchor transform is changed.
We should investigate why `GlobalTransform` change detection seems to trigger so often or, if no real cause is found, investigate all our queries for `Changed<GlobalTransform>` and see how often they get triggered and if we can get away with a simple `Changed<Transform>` instead.
For now this PR fixes panics that occurred when deleting any edge after it was created (the original issue doesn't mention it but walls panic as well)

Fix panic when deleting new edges
